//! Secret Lair Drop grouping.
//!
//! Scryfall breaks the Secret Lair Drop set (`sld`) into named "drops" (e.g.
//! "Wild in Bloom") on its gallery page, but those curated titles are **not** in
//! the bulk card API we ingest — they live only in the page's collector-number
//! groupings. We capture them once into a committed snapshot
//! (`sld_drops.json`, regenerated by `scripts/gen-sld-drops.mjs`) and match each
//! card to its drop by `(game, set_code, collector_number)`.
//!
//! The snapshot is the only source of drop membership; a card whose collector
//! number isn't listed (e.g. a drop released after the snapshot was taken) simply
//! has no drop, and callers fold it into an "Other" group — so a stale snapshot
//! degrades gracefully instead of hiding cards.

use std::collections::HashMap;
use std::sync::OnceLock;

use serde::Deserialize;

/// The committed drop snapshot, embedded at compile time.
const SNAPSHOT_JSON: &str = include_str!("sld_drops.json");

#[derive(Deserialize)]
struct RawSnapshot {
    sets: Vec<RawSetDrops>,
}

#[derive(Deserialize)]
struct RawSetDrops {
    game: String,
    set: String,
    drops: Vec<RawDrop>,
}

#[derive(Deserialize)]
struct RawDrop {
    slug: String,
    title: String,
    collector_numbers: Vec<String>,
}

/// One Secret Lair drop: a curated title plus its position in Scryfall's display
/// order (the snapshot's order, newest first).
#[derive(Debug, Clone)]
pub struct Drop {
    pub slug: String,
    pub title: String,
    /// The drop's card collector numbers (in the set), the join key onto `cards`.
    pub collector_numbers: Vec<String>,
    /// 0-based index in the set's drop order, for stable section ordering.
    pub order: usize,
}

/// A set's drop lookup: the ordered drops plus collector-number and title indexes.
pub struct DropTable {
    drops: Vec<Drop>,
    by_collector: HashMap<String, usize>,
    by_title: HashMap<String, usize>,
}

impl DropTable {
    /// The drop a card belongs to, by collector number, or `None` when the
    /// snapshot doesn't list that number (a newer-than-snapshot printing).
    pub fn drop_for(&self, collector_number: &str) -> Option<&Drop> {
        self.by_collector
            .get(collector_number)
            .map(|&i| &self.drops[i])
    }

    /// The drop whose title matches, comparing on [`normalize_title`] (case- and
    /// punctuation-insensitive). Used to map a Secret Lair *sealed product* to its
    /// drop by name so the drop's cards can populate the product's contents.
    pub fn drop_by_title(&self, normalized_title: &str) -> Option<&Drop> {
        self.by_title.get(normalized_title).map(|&i| &self.drops[i])
    }

    /// The drop with this slug (an exact, curated key — used by product overrides).
    pub fn drop_by_slug(&self, slug: &str) -> Option<&Drop> {
        self.drops.iter().find(|d| d.slug == slug)
    }

    /// Whether the snapshot lists any drops for this set.
    pub fn is_empty(&self) -> bool {
        self.drops.is_empty()
    }
}

/// Canonicalise a drop/product title for case- and punctuation-insensitive matching:
/// lowercased, `&` expanded to `and`, every run of non-alphanumeric characters collapsed
/// to a single space, trimmed. So `"Garfield: Our Only Thought Is To Entertain You"` and
/// the snapshot's `"Garfield: Our Only Thought Is to Entertain You"` both normalise to
/// `"garfield our only thought is to entertain you"`.
pub fn normalize_title(title: &str) -> String {
    let expanded = title.replace('&', " and ");
    let mut out = String::with_capacity(expanded.len());
    let mut pending_space = false;
    for ch in expanded.chars() {
        if ch.is_alphanumeric() {
            if pending_space && !out.is_empty() {
                out.push(' ');
            }
            pending_space = false;
            out.extend(ch.to_lowercase());
        } else {
            pending_space = true;
        }
    }
    out
}

/// Composite map key. A handful of entries (one per drop-grouped set), so the
/// per-lookup `format!` is immaterial.
fn key(game: &str, set_code: &str) -> String {
    format!("{game}/{set_code}")
}

fn tables() -> &'static HashMap<String, DropTable> {
    static TABLES: OnceLock<HashMap<String, DropTable>> = OnceLock::new();
    TABLES.get_or_init(build_tables)
}

fn build_tables() -> HashMap<String, DropTable> {
    let snapshot: RawSnapshot = match serde_json::from_str(SNAPSHOT_JSON) {
        Ok(snapshot) => snapshot,
        Err(err) => {
            // A malformed committed snapshot disables drop grouping rather than
            // taking the server down; `snapshot_parses` guards the shipped file.
            tracing::error!(error = %err, "failed to parse sld_drops.json; drop grouping disabled");
            return HashMap::new();
        }
    };

    let mut tables = HashMap::new();
    for set in snapshot.sets {
        let mut drops = Vec::with_capacity(set.drops.len());
        let mut by_collector = HashMap::new();
        let mut by_title = HashMap::new();
        for (order, raw) in set.drops.into_iter().enumerate() {
            for cn in &raw.collector_numbers {
                // The first drop to list a number keeps it; the snapshot is
                // generated collision-free, but guard against a future dupe
                // silently reassigning a card.
                by_collector.entry(cn.clone()).or_insert(order);
            }
            // Likewise for titles: the first drop with a given normalised title wins,
            // so a rare title collision can't silently reassign the earlier drop.
            by_title.entry(normalize_title(&raw.title)).or_insert(order);
            drops.push(Drop {
                slug: raw.slug,
                title: raw.title,
                collector_numbers: raw.collector_numbers,
                order,
            });
        }
        tables.insert(
            key(&set.game, &set.set),
            DropTable {
                drops,
                by_collector,
                by_title,
            },
        );
    }
    tables
}

/// The raw embedded drop snapshot JSON. Exposed so a caller that derives data *from* the
/// drops (the Secret Lair sealed-contents derivation) can fold the snapshot into its own
/// version gate, so regenerating `sld_drops.json` re-runs that derivation.
pub fn snapshot_json() -> &'static str {
    SNAPSHOT_JSON
}

/// The drop table for a game's set, or `None` if that set isn't drop-grouped.
pub fn table(game: &str, set_code: &str) -> Option<&'static DropTable> {
    tables().get(&key(game, set_code))
}

/// Whether this set is broken into Secret Lair-style drops.
pub fn has_drops(game: &str, set_code: &str) -> bool {
    table(game, set_code).is_some_and(|t| !t.is_empty())
}

/// The drop a single card belongs to, if its set is drop-grouped and the
/// snapshot lists its collector number.
pub fn drop_for(game: &str, set_code: &str, collector_number: &str) -> Option<&'static Drop> {
    table(game, set_code).and_then(|t| t.drop_for(collector_number))
}

/// Curated Secret Lair **spend-incentive** printings: promo cards handed out for reaching a
/// cart spend threshold during a superdrop (e.g. the Avatar: The Last Airbender superdrop's
/// foil Path of Ancestry, one per $199 spent) rather than included with a specific drop.
/// Scryfall tags these `sldbonus` like the per-drop bonus cards, so on their own they read as
/// ordinary chase cards; this list lets the UI call them out distinctly as spend rewards.
/// Keyed by `(game, set_code, collector_number)` — kept tiny and curated, like the SLD
/// product overrides, because there's no upstream signal that separates a spend reward from
/// an ordinary bonus card.
const SPEND_INCENTIVES: &[(&str, &str, &str)] = &[
    // Each superdrop hands out one foil promo per qualifying spend threshold. All in `sld`.
    ("mtg", "sld", "903"), // The Locust God — Secretversary 2023 superdrop
    ("mtg", "sld", "905"), // Cryptic Command — Secret Scare superdrop
    ("mtg", "sld", "906"), // Ignoble Hierarch — Equinox 2024 superdrop
    ("mtg", "sld", "907"), // Seedborn Muse — Spring 2024 superdrop
    ("mtg", "sld", "908"), // Arcane Signet ("Earth's Mightiest Emblem") — Marvel superdrop
    ("mtg", "sld", "912"), // Sol Ring — PlayStation / Twisted Metal superdrop
    ("mtg", "sld", "914"), // Path of Ancestry — Avatar: The Last Airbender superdrop
    ("mtg", "sld", "915"), // Silver Shroud Costume — Fallout / Rad superdrop
    ("mtg", "sld", "918"), // Food Token ("Lasagna") — Garfield superdrop
];

/// Whether a printing is a curated Secret Lair spend-incentive promo (see [`SPEND_INCENTIVES`]).
pub fn is_spend_incentive(game: &str, set_code: &str, collector_number: &str) -> bool {
    SPEND_INCENTIVES
        .iter()
        .any(|&(g, s, cn)| g == game && s == set_code && cn == collector_number)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn snapshot_parses_and_covers_sld() {
        let table = table("mtg", "sld").expect("sld is drop-grouped");
        // The shipped snapshot has hundreds of drops; assert a healthy floor so a
        // truncated/corrupt regeneration is caught.
        assert!(
            table.drops.len() > 100,
            "expected many drops, got {}",
            table.drops.len()
        );
        assert!(has_drops("mtg", "sld"));
    }

    #[test]
    fn known_collector_numbers_resolve_to_their_drop() {
        assert_eq!(
            drop_for("mtg", "sld", "2658").map(|d| d.title.as_str()),
            Some("Wild in Bloom")
        );
        assert_eq!(
            drop_for("mtg", "sld", "168").map(|d| d.title.as_str()),
            Some("Inked")
        );
        // A collector number the snapshot doesn't list -> no drop (folds to "Other").
        assert!(drop_for("mtg", "sld", "this-cn-does-not-exist").is_none());
    }

    #[test]
    fn spend_incentives_are_recognised() {
        // Curated superdrop spend rewards are recognised — the earliest (The Locust God
        // #903), a token promo (Food Token #918), and one in between (Path of Ancestry #914).
        assert!(is_spend_incentive("mtg", "sld", "903"));
        assert!(is_spend_incentive("mtg", "sld", "914"));
        assert!(is_spend_incentive("mtg", "sld", "918"));
        // An ordinary drop card is not; nor is the number in another set or game.
        assert!(!is_spend_incentive("mtg", "sld", "2658"));
        assert!(!is_spend_incentive("mtg", "blb", "914"));
        assert!(!is_spend_incentive("pokemon", "sld", "914"));
    }

    #[test]
    fn non_drop_sets_have_no_table() {
        assert!(table("mtg", "blb").is_none());
        assert!(!has_drops("mtg", "blb"));
        // Unknown game, too.
        assert!(drop_for("pokemon", "sld", "2658").is_none());
    }

    #[test]
    fn first_snapshot_drop_is_order_zero() {
        // Drop order mirrors the snapshot's order; the first drop is 0.
        assert_eq!(drop_for("mtg", "sld", "2658").map(|d| d.order), Some(0));
    }

    #[test]
    fn drops_carry_their_collector_numbers() {
        let table = table("mtg", "sld").expect("sld is drop-grouped");
        let drop = table
            .drop_by_title(&normalize_title("Wild in Bloom"))
            .expect("drop present");
        assert_eq!(
            drop.collector_numbers,
            ["2658", "2659", "2660", "2661", "2662"]
        );
    }

    #[test]
    fn drop_by_title_is_case_and_punctuation_insensitive() {
        let table = table("mtg", "sld").expect("sld is drop-grouped");
        // A product name capitalises "To" where the snapshot writes "to"; normalisation
        // collapses the difference, and the surrounding colon becomes a space.
        let normalized = normalize_title("Garfield: Our Only Thought Is To Entertain You");
        assert_eq!(
            table.drop_by_title(&normalized).map(|d| d.slug.as_str()),
            Some("garfield-our-only-thought-is-to-entertain-you"),
        );
        // A title that matches no drop resolves to nothing.
        assert!(
            table
                .drop_by_title(&normalize_title("Not A Real Drop"))
                .is_none()
        );
    }

    #[test]
    fn drop_by_slug_resolves_curated_overrides() {
        let table = table("mtg", "sld").expect("sld is drop-grouped");
        let drop = table
            .drop_by_slug("secret-lair-presents-nuestra-magia")
            .expect("Nuestra Magia drop present");
        assert_eq!(drop.title, "Secret Lair Presents: Nuestra Magia");
        assert!(table.drop_by_slug("no-such-slug").is_none());
    }

    #[test]
    fn normalize_title_expands_ampersand_and_collapses_separators() {
        assert_eq!(normalize_title("Rock & Roll"), "rock and roll");
        assert_eq!(
            normalize_title("  Witch's  Familiar!! "),
            "witch s familiar"
        );
        assert_eq!(
            normalize_title("FINAL FANTASY: Game Over"),
            "final fantasy game over"
        );
    }
}
