//! Secret Lair Drop grouping.
//!
//! Scryfall breaks the Secret Lair Drop set (`sld`) into named "drops" (e.g.
//! "Wild in Bloom") on its gallery page, but those curated titles are **not** in
//! the bulk card API we ingest — they live only in the page's collector-number
//! groupings. We capture them once into a committed snapshot
//! (`sld_drops.json`, regenerated by `scripts/gen-sld-drops.mjs`) and match each
//! card to its drop by `(game, set_code, collector_number)`.
//!
//! The snapshot is the only source of drop membership; a card whose collector
//! number isn't listed (e.g. a drop released after the snapshot was taken) simply
//! has no drop, and callers fold it into an "Other" group — so a stale snapshot
//! degrades gracefully instead of hiding cards.

use std::collections::HashMap;
use std::sync::OnceLock;

use serde::Deserialize;

/// The committed drop snapshot, embedded at compile time.
const SNAPSHOT_JSON: &str = include_str!("sld_drops.json");

#[derive(Deserialize)]
struct RawSnapshot {
    sets: Vec<RawSetDrops>,
}

#[derive(Deserialize)]
struct RawSetDrops {
    game: String,
    set: String,
    drops: Vec<RawDrop>,
}

#[derive(Deserialize)]
struct RawDrop {
    slug: String,
    title: String,
    collector_numbers: Vec<String>,
}

/// One Secret Lair drop: a curated title plus its position in Scryfall's display
/// order (the snapshot's order, newest first).
#[derive(Debug, Clone)]
pub struct Drop {
    pub slug: String,
    pub title: String,
    /// 0-based index in the set's drop order, for stable section ordering.
    pub order: usize,
}

/// A set's drop lookup: the ordered drops plus a collector-number index into them.
pub struct DropTable {
    drops: Vec<Drop>,
    by_collector: HashMap<String, usize>,
}

impl DropTable {
    /// The drop a card belongs to, by collector number, or `None` when the
    /// snapshot doesn't list that number (a newer-than-snapshot printing).
    pub fn drop_for(&self, collector_number: &str) -> Option<&Drop> {
        self.by_collector
            .get(collector_number)
            .map(|&i| &self.drops[i])
    }

    /// Whether the snapshot lists any drops for this set.
    pub fn is_empty(&self) -> bool {
        self.drops.is_empty()
    }
}

/// Composite map key. A handful of entries (one per drop-grouped set), so the
/// per-lookup `format!` is immaterial.
fn key(game: &str, set_code: &str) -> String {
    format!("{game}/{set_code}")
}

fn tables() -> &'static HashMap<String, DropTable> {
    static TABLES: OnceLock<HashMap<String, DropTable>> = OnceLock::new();
    TABLES.get_or_init(build_tables)
}

fn build_tables() -> HashMap<String, DropTable> {
    let snapshot: RawSnapshot = match serde_json::from_str(SNAPSHOT_JSON) {
        Ok(snapshot) => snapshot,
        Err(err) => {
            // A malformed committed snapshot disables drop grouping rather than
            // taking the server down; `snapshot_parses` guards the shipped file.
            tracing::error!(error = %err, "failed to parse sld_drops.json; drop grouping disabled");
            return HashMap::new();
        }
    };

    let mut tables = HashMap::new();
    for set in snapshot.sets {
        let mut drops = Vec::with_capacity(set.drops.len());
        let mut by_collector = HashMap::new();
        for (order, raw) in set.drops.into_iter().enumerate() {
            for cn in raw.collector_numbers {
                // The first drop to list a number keeps it; the snapshot is
                // generated collision-free, but guard against a future dupe
                // silently reassigning a card.
                by_collector.entry(cn).or_insert(order);
            }
            drops.push(Drop {
                slug: raw.slug,
                title: raw.title,
                order,
            });
        }
        tables.insert(key(&set.game, &set.set), DropTable { drops, by_collector });
    }
    tables
}

/// The drop table for a game's set, or `None` if that set isn't drop-grouped.
pub fn table(game: &str, set_code: &str) -> Option<&'static DropTable> {
    tables().get(&key(game, set_code))
}

/// Whether this set is broken into Secret Lair-style drops.
pub fn has_drops(game: &str, set_code: &str) -> bool {
    table(game, set_code).is_some_and(|t| !t.is_empty())
}

/// The drop a single card belongs to, if its set is drop-grouped and the
/// snapshot lists its collector number.
pub fn drop_for(game: &str, set_code: &str, collector_number: &str) -> Option<&'static Drop> {
    table(game, set_code).and_then(|t| t.drop_for(collector_number))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn snapshot_parses_and_covers_sld() {
        let table = table("mtg", "sld").expect("sld is drop-grouped");
        // The shipped snapshot has hundreds of drops; assert a healthy floor so a
        // truncated/corrupt regeneration is caught.
        assert!(table.drops.len() > 100, "expected many drops, got {}", table.drops.len());
        assert!(has_drops("mtg", "sld"));
    }

    #[test]
    fn known_collector_numbers_resolve_to_their_drop() {
        assert_eq!(drop_for("mtg", "sld", "2658").map(|d| d.title.as_str()), Some("Wild in Bloom"));
        assert_eq!(drop_for("mtg", "sld", "168").map(|d| d.title.as_str()), Some("Inked"));
        // A collector number the snapshot doesn't list -> no drop (folds to "Other").
        assert!(drop_for("mtg", "sld", "this-cn-does-not-exist").is_none());
    }

    #[test]
    fn non_drop_sets_have_no_table() {
        assert!(table("mtg", "blb").is_none());
        assert!(!has_drops("mtg", "blb"));
        // Unknown game, too.
        assert!(drop_for("pokemon", "sld", "2658").is_none());
    }

    #[test]
    fn first_snapshot_drop_is_order_zero() {
        // Drop order mirrors the snapshot's order; the first drop is 0.
        assert_eq!(drop_for("mtg", "sld", "2658").map(|d| d.order), Some(0));
    }
}
