#!/usr/bin/env python3
"""Generate the shared 32-point DCT-II basis matrix as identical f64 literals for
both the Rust reference hasher and the TS/browser query hasher.

Parity between the two implementations comes from baking these EXACT constants into
both languages (not from each platform's own cos()), so the DCT is pure multiply-add
over identical inputs and yields identical f64 results. `repr(float)` emits the
shortest decimal that round-trips to the one nearest IEEE-754 double, which every
correct parser (Rust, JS) maps back to the same double."""
import math, sys

N = 32
alpha0 = math.sqrt(1.0 / N)
alphak = math.sqrt(2.0 / N)


def c(k, n):
    a = alpha0 if k == 0 else alphak
    return a * math.cos(math.pi * (2 * n + 1) * k / (2 * N))


rows = [[c(k, n) for n in range(N)] for k in range(N)]

rust_out = sys.argv[1]
ts_out = sys.argv[2]

# --- Rust ---
with open(rust_out, "w") as f:
    f.write(
        "// @generated by scripts/gen_phash_basis.py — DO NOT EDIT BY HAND.\n"
        "// The 32-point DCT-II basis matrix, baked as f64 literals so the Rust and the\n"
        "// browser (TS) hashers share bit-identical constants — see `web/src/lib/scan/\n"
        "// phash-basis.ts`, which is generated from the same values. Regenerate both with\n"
        "// `python3 scripts/gen_phash_basis.py`.\n\n"
        f"pub const DCT_N: usize = {N};\n\n"
        f"pub static DCT_BASIS: [[f64; {N}]; {N}] = [\n"
    )
    for k in range(N):
        f.write("    [\n")
        for n in range(N):
            f.write(f"        {rows[k][n]!r},\n")
        f.write("    ],\n")
    f.write("];\n")

# --- TypeScript ---
# Emitted as a FLAT row-major Float64Array (index k*N + n) so the browser hasher indexes
# it without nested-array `| undefined` under `noUncheckedIndexedAccess`, and matches the
# f64 numeric semantics of the Rust reference exactly.
with open(ts_out, "w") as f:
    f.write(
        "// @generated by scripts/gen_phash_basis.py — DO NOT EDIT BY HAND.\n"
        "// The 32-point DCT-II basis matrix, baked as f64 literals so this browser hasher\n"
        "// shares bit-identical constants with the Rust reference hasher (api/src/phash/mod.rs).\n"
        "// Flat row-major layout: entry (k, n) is at index k * DCT_N + n. Regenerate both with\n"
        "// `python3 scripts/gen_phash_basis.py`.\n\n"
        f"export const DCT_N = {N}\n\n"
        "export const DCT_BASIS = new Float64Array([\n"
    )
    for k in range(N):
        f.write(f"  // row k={k}\n  ")
        f.write(", ".join(repr(rows[k][n]) for n in range(N)))
        f.write(",\n")
    f.write("])\n")

print(f"wrote {rust_out} and {ts_out}")
print("sample C[0][0] =", repr(rows[0][0]), " C[1][0] =", repr(rows[1][0]))
