import { fileURLToPath, URL } from 'node:url'
import { readFileSync } from 'node:fs'
import type { IncomingMessage, ServerResponse } from 'node:http'

import { defineConfig, type Plugin } from 'vite'
import vue from '@vitejs/plugin-vue'
import vueDevTools from 'vite-plugin-vue-devtools'
import tailwindcss from '@tailwindcss/vite'

// Proxy /api to the backend so the browser stays same-origin (the httpOnly
// refresh cookie is first-party). Shared by the dev server and the preview
// server — the latter backs the production-like e2e run on CI.
const apiProxy = {
  '/api': {
    target: 'http://localhost:8080',
    changeOrigin: true,
  },
}

// Public site URL, used to build the absolute Sitemap: line in robots.txt.
// Canonical/OG URLs are resolved at runtime from the live origin (see
// src/lib/seo.ts). The sitemap itself is now generated by the API — DB-backed
// across games, sets and cards (issue #75) — and served at /api/sitemap.xml, so
// robots.txt just points crawlers at it. Set VITE_SITE_URL in production CI; the
// localhost default keeps dev/e2e valid.
const SITE_URL = (process.env.VITE_SITE_URL ?? 'http://localhost:5173').replace(/\/$/, '')

// The default social/link-preview banner (web/public/og-image.png). index.html carries
// it as a root-relative baseline og:image/twitter:image for readability; we rewrite it
// to an absolute URL below since unfurlers that don't run JS need one (see seo.ts /
// DEFAULT_OG_IMAGE for the runtime, per-route default).
const OG_IMAGE_PATH = '/og-image.png'
const OG_IMAGE_URL = `${SITE_URL}${OG_IMAGE_PATH}`

// App version, read from package.json and injected at build time so the footer can show
// which release is deployed (issue #250). Read here rather than imported so vue-tsc's
// project build doesn't pull package.json (outside src/) into the app's type graph.
const APP_VERSION = (
  JSON.parse(
    readFileSync(fileURLToPath(new URL('./package.json', import.meta.url)), 'utf-8'),
  ) as { version: string }
).version

function robotsTxt(): string {
  return [
    'User-agent: *',
    'Allow: /',
    // Keep auth + signed-in app pages out of the index (also set via `noindex`
    // at runtime, but declared here for non-JS crawlers).
    'Disallow: /login',
    'Disallow: /register',
    'Disallow: /profile',
    'Disallow: /collection',
    'Disallow: /wishlist',
    // The email-flow routes carry secret tokens in the query string.
    'Disallow: /complete-registration',
    'Disallow: /forgot-password',
    'Disallow: /reset-password',
    'Disallow: /verify-email',
    '',
    // The DB-backed sitemap lives on the API (index + chunked child sitemaps).
    `Sitemap: ${SITE_URL}/api/sitemap.xml`,
    '',
  ].join('\n')
}

// Emit robots.txt at build time (correct absolute Sitemap: URL), and serve the
// same content in the dev/preview servers so both environments match. It's
// generated rather than committed to public/ so the URL tracks VITE_SITE_URL and
// can't go stale. The sitemap itself is served by the API (see src/../api's
// handlers::sitemap), so it isn't emitted here. Also rewrites the baseline
// og:image/twitter:image in index.html to an absolute VITE_SITE_URL for non-JS
// unfurlers (see transformIndexHtml below).
function seoDiscoveryFiles(): Plugin {
  const files: Record<string, { body: string; type: string }> = {
    '/robots.txt': { body: robotsTxt(), type: 'text/plain' },
  }
  const handle = (req: IncomingMessage, res: ServerResponse, next: () => void) => {
    const path = req.url?.split('?')[0]
    const file = path ? files[path] : undefined
    if (!file) return next()
    res.setHeader('Content-Type', file.type)
    res.end(file.body)
  }
  return {
    name: 'tcglense-seo-discovery-files',
    // The dev and preview servers expose different types, so register on each.
    configureServer(server) {
      server.middlewares.use(handle)
    },
    configurePreviewServer(server) {
      server.middlewares.use(handle)
    },
    // Rewrite the baseline og:image/twitter:image to an absolute URL (tracking
    // VITE_SITE_URL, like the robots.txt Sitemap: line) so non-JS unfurlers get one.
    transformIndexHtml(html) {
      return html.replaceAll(`content="${OG_IMAGE_PATH}"`, `content="${OG_IMAGE_URL}"`)
    },
    generateBundle() {
      this.emitFile({ type: 'asset', fileName: 'robots.txt', source: robotsTxt() })
    },
  }
}

// https://vite.dev/config/
export default defineConfig({
  define: {
    // Expose the package.json version to the app (consumed in AppFooter.vue). Nothing
    // sets VITE_APP_VERSION via .env, so this define is its sole source — no conflict
    // with Vite's own env injection.
    'import.meta.env.VITE_APP_VERSION': JSON.stringify(APP_VERSION),
  },
  plugins: [vue(), vueDevTools(), tailwindcss(), seoDiscoveryFiles()],
  resolve: {
    alias: {
      '@': fileURLToPath(new URL('./src', import.meta.url)),
    },
  },
  server: {
    proxy: apiProxy,
  },
  preview: {
    proxy: apiProxy,
  },
})
