import { fileURLToPath, URL } from 'node:url'
import { createReadStream, readFileSync } from 'node:fs'
import { createRequire } from 'node:module'
import type { IncomingMessage, ServerResponse } from 'node:http'

import { defineConfig, type Plugin } from 'vite'
import vue from '@vitejs/plugin-vue'
import vueDevTools from 'vite-plugin-vue-devtools'
import tailwindcss from '@tailwindcss/vite'

// Proxy /api to the backend so the browser stays same-origin (the httpOnly
// refresh cookie is first-party). The root sitemap paths are served by the API
// too (issue #294), mirroring the production proxies (deploy/*.Caddyfile).
// Shared by the dev server and the preview server — the latter backs the
// production-like e2e run on CI.
const apiProxy = {
  '/api': {
    target: 'http://localhost:8080',
    changeOrigin: true,
  },
  '/sitemap.xml': {
    target: 'http://localhost:8080',
    changeOrigin: true,
  },
  '/sitemaps': {
    target: 'http://localhost:8080',
    changeOrigin: true,
  },
}

// Public site URL, used to build the absolute Sitemap: line in robots.txt.
// Canonical/OG URLs are resolved at runtime from the live origin (see
// src/lib/seo.ts). The sitemap itself is generated by the API — DB-backed across
// games, sets, cards, and sealed products (issues #75/#294) — and served at the
// root /sitemap.xml, so robots.txt just points crawlers at it. Set VITE_SITE_URL
// in production CI; the localhost default keeps dev/e2e valid.
const SITE_URL = (process.env.VITE_SITE_URL ?? 'http://localhost:5173').replace(/\/$/, '')

// The default social/link-preview banner (web/public/og-image.png). index.html carries
// it as a root-relative baseline og:image/twitter:image for readability; we rewrite it
// to an absolute URL below since unfurlers that don't run JS need one (see seo.ts /
// DEFAULT_OG_IMAGE for the runtime, per-route default).
const OG_IMAGE_PATH = '/og-image.png'
const OG_IMAGE_URL = `${SITE_URL}${OG_IMAGE_PATH}`

// App version, read from package.json and injected at build time so the footer can show
// which release is deployed (issue #250). Read here rather than imported so vue-tsc's
// project build doesn't pull package.json (outside src/) into the app's type graph.
const APP_VERSION = (
  JSON.parse(
    readFileSync(fileURLToPath(new URL('./package.json', import.meta.url)), 'utf-8'),
  ) as { version: string }
).version

function robotsTxt(): string {
  return [
    'User-agent: *',
    'Allow: /',
    // Keep auth + signed-in app pages out of the index (also set via `noindex`
    // at runtime, but declared here for non-JS crawlers).
    'Disallow: /login',
    'Disallow: /register',
    'Disallow: /profile',
    'Disallow: /collection',
    'Disallow: /wishlist',
    // The email-flow routes carry secret tokens in the query string.
    'Disallow: /complete-registration',
    'Disallow: /forgot-password',
    'Disallow: /reset-password',
    'Disallow: /verify-email',
    '',
    // The DB-backed sitemap index (chunked child sitemaps under /sitemaps/),
    // served by the API at the site root.
    `Sitemap: ${SITE_URL}/sitemap.xml`,
    '',
  ].join('\n')
}

// /llms.txt — the emerging convention (llmstxt.org) for an LLM/agent-friendly map of a
// site. TCGLense is API-first (a public, CDN-cacheable JSON catalog plus scoped `tcgl_`
// keys), so this is a curated entry point that points agents straight at the
// machine-readable OpenAPI spec and the main endpoint groups instead of scraping the SPA.
// Built from VITE_SITE_URL for the same reason robots.txt is (absolute links must track
// the origin); it needs no database, so — unlike the sitemap — it's a static build-time
// file, not an API route. Keep the endpoint facts in sync with docs/api-contracts.md.
function llmsTxt(): string {
  return `# TCGLense

> TCGLense is a self-hostable trading-card-game tracker with a public, read-friendly JSON API. It serves a card catalog (Magic: The Gathering first, sourced from Scryfall), daily price history for singles and sealed products, and — with a scoped API key — a signed-in user's own collection and wish list.

The entire public catalog is anonymous, JSON, and CDN-cacheable; only per-user data needs a key. Every endpoint lives under \`/api\`, and the complete contract is published as OpenAPI 3.1, so an agent can read the spec directly instead of scraping the HTML app.

- Base URL: \`${SITE_URL}/api\`
- All responses are JSON. Errors are always \`{ "error": string }\` with a matching HTTP status.
- Primary game slug: \`mtg\` (call \`GET /api/games\` for the live list).

## API reference

- [OpenAPI 3.1 specification](${SITE_URL}/api/openapi.json): the complete, machine-readable contract — every endpoint, query parameter, and response shape. This is the authoritative source; prefer it over this file for exact details.
- [Interactive API docs](${SITE_URL}/docs): a "try it out" reference (Scalar) rendered from the same spec.

## Public catalog (no authentication)

- \`GET /api/games\` — supported games.
- \`GET /api/games/{game}/sets\` — a game's sets, newest first.
- \`GET /api/games/{game}/cards?q=&page=&page_size=\` — search cards. \`q\` accepts (near-)full Scryfall syntax, e.g. \`c:red t:instant cmc<=2\`. Paging is 1-based; \`page_size\` defaults to 60 (max 200).
- \`GET /api/games/{game}/cards/{id}\` — one card, with its current prices.
- \`GET /api/games/{game}/cards/{id}/prices?range=\` — daily price history; \`range\` is one of \`7d\`, \`30d\`, \`1y\`, \`2y\`, \`3y\`, \`all\`.
- \`GET /api/games/{game}/cards/{id}/prints\` — other printings of the same card.
- \`GET /api/games/{game}/products?q=&set=&type=&sort=&dir=\` — sealed products (booster boxes, bundles, decks, …).
- \`GET /api/games/{game}/products/{id}/prices?range=\` — sealed-product price history.

Prices are decimal strings and may be \`null\`: cards carry \`usd\`, \`usd_foil\`, \`eur\`, \`tix\`; sealed products carry \`usd\`, \`usd_foil\` — passed through as stored, with no display-currency conversion. Public reads are shared-cacheable (\`Cache-Control: public, s-maxage=…\`) and support \`ETag\` / \`If-None-Match\` revalidation.

## Authenticated API (per-user, API key)

A signed-in user mints a scoped API key in the web app and presents it exactly like a session token: \`Authorization: Bearer tcgl_<hex>\`. A key reaches only its owner's data.

- Scopes: \`read\` (read endpoints only) or \`read_write\`. A read-only key on a write is \`403\`; a bad, expired, or revoked key is \`401\`.
- \`GET /api/collection/{game}\` — the caller's owned cards. \`PUT /api/collection/{game}/cards/{id}\` upserts a holding.
- \`GET /api/wishlist/{game}\` — the caller's wish list (same shape as the collection).
- \`GET /api/collection/{game}/summary\`, \`.../value-history\`, \`.../movers\` — totals, collection value over time, and the biggest price movers.
- Key management (\`/api/auth/api-keys\`) is session-only: an API key cannot mint or revoke keys.

## Discovery & clients

- [Sitemap index](${SITE_URL}/sitemap.xml): every catalog page (games, sets, cards, sealed products), for crawlers.
- Rate limits apply to both public and per-user traffic; over-limit is \`429\` with a \`Retry-After\` header.
- A command-line client and TUI over this same API: https://github.com/PNRxA/tcglense-cli
`
}

// Emit the site-root discovery files (robots.txt for crawlers, llms.txt for
// LLM/agent clients) at build time — each with correct absolute URLs — and serve the
// same content in the dev/preview servers so both environments match. They're
// generated rather than committed to public/ so their URLs track VITE_SITE_URL and
// can't go stale. The sitemap itself is served by the API (see src/../api's
// handlers::sitemap), so it isn't emitted here. Also rewrites the baseline
// og:image/twitter:image in index.html to an absolute VITE_SITE_URL for non-JS
// unfurlers (see transformIndexHtml below).
function seoDiscoveryFiles(): Plugin {
  const files: Record<string, { body: string; type: string }> = {
    '/robots.txt': { body: robotsTxt(), type: 'text/plain' },
    // llms.txt is Markdown, but a `.txt` file server hands it back as text/plain in
    // production; match that in dev, with an explicit UTF-8 charset for the em-dashes.
    '/llms.txt': { body: llmsTxt(), type: 'text/plain; charset=utf-8' },
  }
  const handle = (req: IncomingMessage, res: ServerResponse, next: () => void) => {
    const path = req.url?.split('?')[0]
    const file = path ? files[path] : undefined
    if (!file) return next()
    res.setHeader('Content-Type', file.type)
    res.end(file.body)
  }
  return {
    name: 'tcglense-seo-discovery-files',
    // The dev and preview servers expose different types, so register on each.
    configureServer(server) {
      server.middlewares.use(handle)
    },
    configurePreviewServer(server) {
      server.middlewares.use(handle)
    },
    // Rewrite the baseline og:image/twitter:image to an absolute URL (tracking
    // VITE_SITE_URL, like the robots.txt Sitemap: line) so non-JS unfurlers get one.
    transformIndexHtml(html) {
      return html.replaceAll(`content="${OG_IMAGE_PATH}"`, `content="${OG_IMAGE_URL}"`)
    },
    // Emit every discovery file from the same map the dev/preview middleware serves,
    // so the two paths can't drift and adding one is a single `files` entry.
    generateBundle() {
      for (const [path, file] of Object.entries(files)) {
        this.emitFile({ type: 'asset', fileName: path.slice(1), source: file.body })
      }
    },
  }
}

// The card scanner's OCR runtime, self-hosted (issue #451). tesseract.js's browser
// defaults download its worker, wasm core, and traineddata from cdn.jsdelivr.net at
// runtime and run them with the app origin's privileges — a supply-chain exposure the
// rest of the app doesn't have (the sibling OpenCV runtime is npm-bundled). Instead,
// `useCardScanner.ts` points createWorker at the same-origin paths below, and this
// plugin publishes the matching files from the lockfile-pinned packages: emitted into
// the build for production, streamed straight out of node_modules in dev.
//
// The shape is constrained by tesseract.js: `corePath`/`langPath` are *directories*, and
// the worker picks a core build by SIMD feature-detection against these exact filenames
// — so the files must keep canonical, unhashed names (no `?url` imports, which emit
// hashed names). Unhashed names need revalidation, not `immutable`: the API's SPA
// fallback serves non-`/assets/` paths `public, no-cache`, and the Caddy file-server
// topologies set the same header on /tesseract/* explicitly (deploy/Caddyfile,
// deploy/web.Caddyfile). Only the `-lstm` cores are published: the scanner pins
// OEM.LSTM_ONLY, and the published traineddata (`best_int`) carries no legacy model, so
// the legacy cores could never initialise anyway. Everything here is fetched lazily when
// the scanner first opens; tesseract.js then caches the traineddata in IndexedDB, where
// a returning browser reads it before ever re-fetching (see docs/tradeoffs.md).
const TESSERACT_ASSETS: Record<string, string> = {
  'tesseract/worker.min.js': 'tesseract.js/dist/worker.min.js',
  // worker.min.js ends with a sourceMappingURL comment; publish the map beside it or
  // DevTools chases it into the SPA's index.html fallback and logs parse noise.
  'tesseract/worker.min.js.map': 'tesseract.js/dist/worker.min.js.map',
  'tesseract/core/tesseract-core-lstm.wasm.js': 'tesseract.js-core/tesseract-core-lstm.wasm.js',
  'tesseract/core/tesseract-core-simd-lstm.wasm.js':
    'tesseract.js-core/tesseract-core-simd-lstm.wasm.js',
  'tesseract/core/tesseract-core-relaxedsimd-lstm.wasm.js':
    'tesseract.js-core/tesseract-core-relaxedsimd-lstm.wasm.js',
  'tesseract/lang/eng.traineddata.gz': '@tesseract.js-data/eng/4.0.0_best_int/eng.traineddata.gz',
}

function tesseractAssets(): Plugin {
  // require.resolve (none of the three packages restrict subpaths via `exports`) rather
  // than a hard-coded node_modules layout.
  const require = createRequire(import.meta.url)
  const sources = Object.fromEntries(
    Object.entries(TESSERACT_ASSETS).map(([out, pkgPath]) => [out, require.resolve(pkgPath)]),
  )
  return {
    name: 'tcglense-tesseract-assets',
    configureServer(server) {
      server.middlewares.use((req, res, next) => {
        const path = req.url?.split('?')[0]
        // Object.hasOwn, not a bare index: a plain-object lookup would answer
        // /constructor-style URLs with Object.prototype members and 500 instead of
        // falling through to the SPA.
        const key = path?.startsWith('/') ? path.slice(1) : ''
        if (!Object.hasOwn(sources, key)) return next()
        const source = sources[key]
        // Workers need a JS MIME type; the traineddata is opaque bytes (tesseract.js
        // sniffs the gzip magic itself — Vite doesn't Content-Encoding .gz files, and
        // neither do the production file servers).
        res.setHeader(
          'Content-Type',
          source.endsWith('.js') ? 'text/javascript' : 'application/octet-stream',
        )
        // A vanished source (node_modules mid-reinstall) must 500 this request — .pipe()
        // doesn't forward stream errors, and unhandled they kill the dev server process.
        createReadStream(source).on('error', next).pipe(res)
      })
    },
    generateBundle() {
      for (const [fileName, source] of Object.entries(sources)) {
        this.emitFile({ type: 'asset', fileName, source: readFileSync(source) })
      }
    },
  }
}

// https://vite.dev/config/
export default defineConfig({
  define: {
    // Expose the package.json version to the app (consumed in AppFooter.vue). Nothing
    // sets VITE_APP_VERSION via .env, so this define is its sole source — no conflict
    // with Vite's own env injection.
    'import.meta.env.VITE_APP_VERSION': JSON.stringify(APP_VERSION),
  },
  plugins: [vue(), vueDevTools(), tailwindcss(), seoDiscoveryFiles(), tesseractAssets()],
  resolve: {
    alias: {
      '@': fileURLToPath(new URL('./src', import.meta.url)),
    },
  },
  server: {
    proxy: apiProxy,
  },
  preview: {
    proxy: apiProxy,
  },
})
